
image: node:16.14.0
# Remove comments to use the pipeline only on merge request
# Only work with a updated GitLab Runner at V11.9+
# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'

# Cache modules using lock file
cache:
  key:
    files:
      - package-lock.json
    prefix: $CI_PROJECT_TITLE
  paths:
    - .npm/

stages:
  - build
  - tests

before_script:
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    # Building web app
    - echo "Building web app..."
    - CI=false npm run build
    - echo "Build complete."
  interruptible: true

tests:
  stage: tests
  script:
    # Running unit tests
    - echo "Running unit tests..."
    - CI=true npm run test:ci
  interruptible: true