
image: node:16.14.0
# Remove comments to use the pipeline only on merge request
# workflow:
#   rules:
#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#     - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'

stages:
  - install
  - build
  - tests
  - clean

install:
  stage: install
  script:
    # Install web app dependencies
    - echo "Installing npm packages..."
    - npm install --loglevel warn
  cache:
    # Create pipeline scoped cache
    policy: push
    key: "$CI_PIPELINE_ID"
    paths:
      - node_modules/
  interruptible: true

build:
  stage: build
  script:
    # Building web app
    - echo "Building web app..."
    - CI=false npm run build # Remove "CI=false" once the teams will have fixed all lint problems
    - echo "Build complete."
  cache:
    policy: pull
    key: "$CI_PIPELINE_ID"
    paths:
      - node_modules/
  interruptible: true

tests:
  stage: tests
  script:
    # Running unit tests
    - echo "Running unit tests..."
    - CI=true npm run test:ci
  cache:
    policy: pull
    key: "$CI_PIPELINE_ID"
    paths:
      - node_modules/
  interruptible: true

clean:
  stage: clean
  script:
    # Clean pipeline scoped cache
    - rm -rf /cache/trudel_syl/fitnesshabits/$CI_PIPELINE_ID*
  interruptible: true