
image: node:16.14.0
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'master'
    - if: $CI_COMMIT_BRANCH == 'master' # Assure a pipeline status on master
    - if: $CI_PIPELINE_SOURCE == "web" # Allow user to launch manual pipeline

# Cache modules using lock file
cache:
  key:
    files:
      - package-lock.json
    prefix: $CI_PROJECT_TITLE
  paths:
    - .npm/

stages:
  - build
  - tests
  - lint

before_script:
  - npm ci --cache .npm --prefer-offline

build:
  stage: build
  script:
    # Building web app
    - echo "Building web app..."
    - CI=false npm run build
    - echo "Build complete."
  interruptible: true

tests:
  stage: tests
  script:
    # Running unit tests
    - echo "Running unit tests..."
    - CI=true npm run test:ci
  interruptible: true

lint:
  stage: lint
  script:
    # Running lint
    - echo "Running lint..."
    - npm run lint
  interruptible: true